AWSTemplateFormatVersion: "2010-09-09"
Description: "CI lab - secure S3 bucket baseline (SSE-KMS, versioning, public access block, access logging, TLS-only)"

Parameters:
  BucketName:
    Type: String
    Description: "Globally unique S3 bucket name"
    MinLength: 3

Resources:
  BucketKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "KMS key for S3 encryption"
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowAccountRootAdmin
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"

  AuditLogBucket:
    Type: AWS::S3::Bucket
    Metadata:
      checkov:
        skip:
          - id: "CKV_AWS_18"
            comment: "AuditLogBucket is the terminal destination for S3 server access logs; enabling logging on it would create an infinite logging chain."
    Properties:
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # Allow S3 logging service to write access logs into AuditLogBucket
  AuditLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AuditLogBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowS3ServerAccessLogs
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "arn:aws:s3:::${AuditLogBucket}/*"
            Condition:
              StringEquals:
                "aws:SourceAccount": !Ref AWS::AccountId

  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      LoggingConfiguration:
        DestinationBucketName: !Ref AuditLogBucket
        LogFilePrefix: "logbucket-access-logs/"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  SecureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucket
        LogFilePrefix: "access-logs/"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt BucketKmsKey.Arn

  SecureBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SecureBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::${SecureBucket}"
              - !Sub "arn:aws:s3:::${SecureBucket}/*"
            Condition:
              Bool:
                "aws:SecureTransport": false

Outputs:
  BucketNameOut:
    Value: !Ref SecureBucket
  KmsKeyArnOut:
    Value: !GetAtt BucketKmsKey.Arn
